package io.warmup.framework.asm;

import io.warmup.framework.common.ConstructorMetadata;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import org.objectweb.asm.ClassVisitor;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

class ConstructorFinder extends ClassVisitor {

    private final String className;
    private final List<ConstructorMetadata> constructors = new ArrayList<>();
    private boolean hasDefaultConstructor = false;

    public ConstructorFinder(String className) {
        super(Opcodes.ASM9);
        this.className = Objects.requireNonNull(className, "ClassName cannot be null");
    }

    @Override
    public MethodVisitor visitMethod(int access, String name, String descriptor,
            String signature, String[] exceptions) {
        if (name.equals("<init>")) {
            // Skip synthetic constructors (generated by compiler for inner classes, enums, etc.)
            if ((access & Opcodes.ACC_SYNTHETIC) != 0) {
                return null;
            }

            return new ConstructorAnalyzer(className, access, descriptor, constructors);
        }
        return null;
    }

    public ConstructorMetadata getBestConstructor() {
        if (constructors.isEmpty()) {
            return createDefaultConstructor();
        }

        // Strategy: Prefer public no-arg constructor
        ConstructorMetadata publicNoArg = findPublicNoArgConstructor();
        if (publicNoArg != null) {
            return publicNoArg;
        }

        // Strategy: Prefer any no-arg constructor  
        ConstructorMetadata anyNoArg = findAnyNoArgConstructor();
        if (anyNoArg != null) {
            return anyNoArg;
        }

        // Strategy: Prefer public constructor with fewest parameters
        ConstructorMetadata publicWithFewestParams = findPublicConstructorWithFewestParams();
        if (publicWithFewestParams != null) {
            return publicWithFewestParams;
        }

        // Fallback: Constructor with fewest parameters
        return findConstructorWithFewestParams();
    }

    // Helper methods for constructor selection strategies
    private ConstructorMetadata findPublicNoArgConstructor() {
        for (ConstructorMetadata metadata : constructors) {
            if (metadata.isPublic && metadata.parameterCount == 0) {
                return metadata;
            }
        }
        return null;
    }

    private ConstructorMetadata findAnyNoArgConstructor() {
        for (ConstructorMetadata metadata : constructors) {
            if (metadata.parameterCount == 0) {
                return metadata;
            }
        }
        return null;
    }

    private ConstructorMetadata findPublicConstructorWithFewestParams() {
        ConstructorMetadata result = null;
        for (ConstructorMetadata metadata : constructors) {
            if (metadata.isPublic) {
                if (result == null || metadata.parameterCount < result.parameterCount) {
                    result = metadata;
                }
            }
        }
        return result;
    }

    private ConstructorMetadata findConstructorWithFewestParams() {
        ConstructorMetadata result = constructors.get(0);
        for (ConstructorMetadata metadata : constructors) {
            if (metadata.parameterCount < result.parameterCount) {
                result = metadata;
            }
        }
        return result;
    }

    private ConstructorMetadata createDefaultConstructor() {
        return new ConstructorMetadata(className, new String[0], new String[0], 0, true);
    }

    // Additional utility methods
    public List<ConstructorMetadata> getAllConstructors() {
        return new ArrayList<>(constructors);
    }

    public boolean hasPublicNoArgConstructor() {
        return findPublicNoArgConstructor() != null;
    }

    public boolean hasAnyNoArgConstructor() {
        return findAnyNoArgConstructor() != null;
    }

    public int getConstructorCount() {
        return constructors.size();
    }

    // Method to find constructor by parameter count
    public ConstructorMetadata findConstructorByParameterCount(int paramCount) {
        for (ConstructorMetadata metadata : constructors) {
            if (metadata.parameterCount == paramCount) {
                return metadata;
            }
        }
        return null;
    }
}
